.section "Level1Palette" free 
; ============================================================================= 
; Made with makebg 08-03-2016 20:45:03,75 
; ============================================================================= 
Level1PaletteSize: 
 .db 16 ; Number of colors 
Level1Palette: 
.dw $0862 $0BB2 $0FFF $00F0 $00FF $00A0 $0050 $0000 $0AAA $0005 $00AF $005A $0FAF $0532 $0BB2 $0FFA 
Level1PaletteEnd: 
.ends 
