.section "Level2Palette" free 
; ============================================================================= 
; Made with makebg 25-02-2016 14:28:07,14 
; ============================================================================= 
Level2PaletteSize: 
 .db 14 ; Number of colors 
Level2Palette: 
.dw $0422 $0000 $0F5A $0FAA $0AAA $0211 $0005 $0FFF $05CC $0266 $005A $08EE $0000 $005F 
Level2PaletteEnd: 
.ends 
